// <auto-generated />
using System;
using CardService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CardService.Domain.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CardNumberHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("card_number_hash");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<long>("CreditLimitCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("credit_limit_cents");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .HasColumnName("last4");

                    b.HasKey("Id");

                    b.HasIndex("CardNumberHash")
                        .IsUnique();

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("CardService.Domain.Entities.FxRateCacheEntry", b =>
                {
                    b.Property<string>("CurrencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_key");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("record_date");

                    b.Property<DateTime>("CachedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("cached_utc");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("NUMERIC")
                        .HasColumnName("exchange_rate");

                    b.HasKey("CurrencyKey", "RecordDate");

                    b.HasIndex("CurrencyKey", "RecordDate")
                        .IsDescending(false, true);

                    b.ToTable("fx_rate_cache", (string)null);
                });

            modelBuilder.Entity("CardService.Domain.Entities.PurchaseTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_cents");

                    b.Property<Guid>("CardId")
                        .HasColumnType("TEXT")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_date");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CardId", "TransactionDate");

                    b.ToTable("purchases", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
